spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.25.10.32:3306/pc_game_record?useUnicode\=true&characterEncoding\=utf8
    username: record_rambo
    password: VsHE1mBg499Q4uUXMzt1dEh7wcaSFemOPpwuhvQ3x3x7tIGYXf+p8lAyzpcV3OXLu5lC3zGcR2J1ASNtNr2gqQ==
    connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKMT4g1gI/6Yi57pF+h+Qy3ULTYFkqgzyV0TDKD9K3kb7xh5w+pxeSMYamv9LVsbTdJC/iaxYUpfTn466lmBK7cCAwEAAQ==
    initialSize: 5
    minIdle: 5
    maxActive: 100
    maxWait: 60000
    validationQuery: SELECT 1
    filters: config,stat
    testWhileIdle: true
    removeAbandoned: true
    removeAbandonedTimeout: 180
    logAbandoned: true
  jpa:
    properties:
      hibernate:
        show_sql: true
            
server:
  port: 8099
  context-path: /pc-record

security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false