spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/local_pc_game?useUnicode\=true&characterEncoding\=utf8&autoReconnect\=true
    username: root
    password: root
    connectionProperties: config.decrypt=false;
    initialSize: 20
    minIdle: 10
    maxActive: 100
    maxWait: 60000
    time-between-eviction-runs-millis: 60000
    validationQuery: SELECT 1
    filters: config,stat,wall
    testWhileIdle: true
    removeAbandoned: true
    removeAbandonedTimeout: 180
    logAbandoned: true

  activemq:
    broker-url: failover:(tcp://127.0.0.1:61616)?randomize=false&jms.redeliveryPolicy.maximumRedeliveries=3
    in-memory: false
    user: admin
    password: admin
    packages:
      trust-all: true
    pool:
      enabled: true
      configuration:
        block-if-session-pool-is-full: true
        max-connections: 500
      idle-timeout: 5
      expiry-timeout: 5
  #reids
  redis:
    database: 1
    host: 10.10.200.254
    password: ZDU0NTlkNDY5NWZi
    port: 6379
    pool:
      max-idle: 300
      min-idle: 100
      max-active: 300
      max-wait: -1
    timeout: 2000
  jms:
    listener:
      acknowledge-mode: auto
  jpa:
    properties:
      hibernate:
        show_sql: true

server:
  port: 8010
  context-path: /pc-statements

security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false