spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/local_pc_game
    username: root
    password: root
    connectionProperties: config.decrypt=false;
    initialSize: 5
    minIdle: 5
    maxActive: 100
    maxWait: 60000
    validationQuery: SELECT 1
    filters: config,stat,wall
    testWhileIdle: true
#   removeAbandoned: true
#   removeAbandonedTimeout: 180
#   logAbandoned: true

  jpa:
    properties:
      hibernate:
        show_sql: true
#reids
  redis: 
    database: 2
    host: 10.10.100.170
    port: 6379
    pool: 
      max-idle: 300
      min-idle: 100
      max-active: 300
      max-wait: -1
    timeout: 2000

server:
  port: 8090
  context-path: /pc-redis-provider

security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false   
    