spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.25.10.32:3306/pc_game?useUnicode\=true&characterEncoding\=utf8
    username: game_rambo
    password: P1UvhqjqeZvpGZRQVH8g2uAscjCBIgwy3qVrLvUQND2ZknsMIPbKkSoHKWcRiOev/zYgfbr/9LIh8NrakJr5BA==
    connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIDO3H7Rhbp1xc2v6oFSLs4qGpHwRfen8T2UYOka7zBOKlKIAk1xdNpmGZ/j1tHwbz3aW834zIXrWQ27wAn+DgECAwEAAQ==
    initialSize: 50
    minIdle: 20
    maxActive: 100
    maxWait: 60000
    validationQuery: SELECT 1
    filters: config,stat
    testWhileIdle: true
  redis:
    database: 1
    host: 172.25.254.1
    password: NzMwMWUyODViZjQ0
    port: 6379
    pool:
      max-idle: 300
      min-idle: 100
      max-active: 300
      max-wait: -1
    timeout: 2000
  jpa:
    properties:
      hibernate:
        show_sql: true
server:
  port: 8094
  context-path: /pc-redis-provider
security:
  basic:
    enabled: false
management:
  security:
    enabled: false