spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/local_pc_game
    username: root
    password: root
    connectionProperties: config.decrypt=false;
    initialSize: 5
    minIdle: 5
    maxActive: 100
    maxWait: 60000
    validationQuery: SELECT 1
    filters: config,stat
    testWhileIdle: true
#activemq
  activemq:
    broker-url: failover:(tcp://10.0.1.128:61616,tcp://10.0.1.129:61616,tcp://10.0.1.130:61616)?initialReconnectDelay=100&timeout=3000&jms.optimizeAcknowledge=true&jms.optimizeAcknowledgeTimeOut=30000&jms.redeliveryPolicy.maximumRedeliveries=6
    in-memory: false
    user: admin
    password: admin
    packages:
      trust-all: true
    pool:
      enabled: true
      configuration:
        block-if-session-pool-is-full: true
        max-connections: 500
      idle-timeout: 5
      expiry-timeout: 5
      
  redis:
    database: 1
    host: 10.10.200.254
    password: ZDU0NTlkNDY5NWZi
    port: 6379
    pool:
      max-idle: 5000
      min-idle: 5000
      max-active: 5000
      max-wait: 10000
    timeout: 2000
  jpa:
    properties:
      hibernate:
        show_sql: true

server:
  port: 8093
  context-path: /pc-task

security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false