spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.0.207:3306/pc_game?useUnicode\=true&characterEncoding\=utf8&autoReconnect\=true
    username: root
    password: aYXL1OwrUtyIGhV7rQb1JrBYEknfhxaDvNsfVTVUl2Ud/8yfVfrTG80qsmmAUTTY7PvbU7MWa286za5QQSEJ1w==
    connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALIFw4CdWC+r5oRemDurOVtccwbpdh1VEC6VoNzHrppEzhwQyDFvW8gPzJUJ77VtlaS62c6H9BWJfq4Kc/XbPLsCAwEAAQ==
    initialSize: 200
    minIdle: 50
    maxActive: 500
    maxWait: 60000
    validationQuery: SELECT 1
    filters: config,stat,wall
    testWhileIdle: true
  activemq:
    broker-url: failover:(tcp://10.0.1.128:61616,tcp://10.0.1.129:61616,tcp://10.0.1.130:61616)?initialReconnectDelay=100&timeout=3000&jms.optimizeAcknowledge=true&jms.optimizeAcknowledgeTimeOut=30000&jms.redeliveryPolicy.maximumRedeliveries=6
    in-memory: false
    user: admin
    password: admin
    packages:
      trust-all: true
    pool:
      enabled: true
      configuration:
        block-if-session-pool-is-full: true
        max-connections: 500
      idle-timeout: 5
      expiry-timeout: 5
  redis:
    database: 0
    host: 10.10.100.170
    port: 6379
    pool:
      max-idle: 300
      min-idle: 100
      max-active: 300
      max-wait: -1
    timeout: 2000
  jpa:
    properties:
      hibernate:
        show_sql: false
server:
  port: 8099
  context-path: /pc-bet
security:
  basic:
    enabled: false
management:
  security:
    enabled: false