spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.0.207:3306/pc_game?useUnicode\=true&characterEncoding\=utf8
    username: root
#    password: MTA3YjM1MTlmMzM0
    password: aYXL1OwrUtyIGhV7rQb1JrBYEknfhxaDvNsfVTVUl2Ud/8yfVfrTG80qsmmAUTTY7PvbU7MWa286za5QQSEJ1w==
    connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALIFw4CdWC+r5oRemDurOVtccwbpdh1VEC6VoNzHrppEzhwQyDFvW8gPzJUJ77VtlaS62c6H9BWJfq4Kc/XbPLsCAwEAAQ==
    initialSize: 5
    minIdle: 5
    maxActive: 100
    maxWait: 60000
    validationQuery: SELECT 1
    filters: config,stat
    testWhileIdle: true
#    removeAbandoned: true
#    removeAbandonedTimeout: 180
#    logAbandoned: true
#reids
  redis: 
    database: 0
    host: 10.10.100.170
    port: 6379
    pool: 
      max-idle: 300
      min-idle: 100
      max-active: 300
      max-wait: -1
    timeout: 2000

  jpa:
    properties:
      hibernate:
        show_sql: true

server:
  port: 8090
  context-path: /pc-limit

security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false
    

    