spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.25.10.32:3306/pc_game?useUnicode\=true&characterEncoding\=utf8
    username: game_rambo
    password: q0JBrBFu3IQL35J7+mHzb6kAHVS471nulMMkVQieBsZ25z25+Ge4NA5GEvkHmIyKgu0SHfJL6VayenWS81OlfQ==
    connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALaUlIqKz64nQZneVJnZCUkEF++D6pKmDtM+HP3tSh2g1mHio1xtmWlpzUAATHCuH+whTmknBMgW5LyX747bbRUCAwEAAQ==
    initialSize: 5
    minIdle: 5
    maxActive: 100
    maxWait: 60000
    validationQuery: SELECT 1
    filters: config,stat
    testWhileIdle: true
    removeAbandoned: true
    removeAbandonedTimeout: 180
    logAbandoned: true
#reids
  redis: 
    database: 1
    host: 172.25.254.1
    password: NzMwMWUyODViZjQ0
    port: 6379
    pool: 
      max-idle: 300
      min-idle: 100
      max-active: 300
      max-wait: -1
    timeout: 2000

  jpa:
    properties:
      hibernate:
        show_sql: true

server:
  port: 8099
  context-path: /pc-limit

security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false