spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.200.255:3306/pc_game?useUnicode\=true&characterEncoding\=utf8&autoReconnect\=true
    username: root
    password: OKQjzN7dN1TZVUuxtReBTHY44cp15didXxB1HMJZhrydOZ58Dwy4qm5rNUfpj7fIv4YEvX5eO2d4SsI3aQGZhA==
    connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJ0StQ+Xh9habvDCXqB1TOMkBaco8xReSYYuRhJS8KqRJIPxUhiiIcNTgfIeEqp5IpDJwQG0Xs1oLkIrsqHoIdUCAwEAAQ==
    initialSize: 20
    minIdle: 10
    maxActive: 100
    maxWait: 60000
    time-between-eviction-runs-millis: 60000
    validationQuery: SELECT 1
    filters: config,stat,wall
    testWhileIdle: true
  activemq:
    broker-url: tcp://10.10.200.7:61616
    in-memory: false
    user: admin
    password: admin
    packages:
      trust-all: true
    pool:
      max-connections: 500
      enabled: true
      configuration:
        block-if-session-pool-is-full: true
        max-connections: 500
        reconnect-on-exception: true
      idle-timeout: 5
      expiry-timeout: 5
  redis:
    database: 1
    host: 10.10.200.254
    password: ZDU0NTlkNDY5NWZi
    port: 6379
    pool:
      max-idle: 300
      min-idle: 100
      max-active: 300
      max-wait: -1
    timeout: 2000
  jms:
    listener:
      acknowledge-mode: auto
  jpa:
    properties:
      hibernate:
        show_sql: true
        connection:
          autoReconnect: true
          autoReconnectForPools: true
          is-connection-validation-required: true
server:
  port: 18099
  context-path: /pc-payoff
security:
  basic:
    enabled: false
management:
  security:
    enabled: false