spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.200.255:3306/pc_game?useUnicode\=true&characterEncoding\=utf8&autoReconnect\=true
    username: root
    password: k7VqvQSWgN9FYB9kcheiD9VYk5jmU2AosuTS7NiiAwfbPjHs9QACSab81kh9SEoeVOc34k+sGaCA6cDAmI/D9Q==
    connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAN+p5nLVsEWh5I24zKhZzpbVlNxBsqBPJO2exeEvgAWYjYCDCnaEGpCk0GECLHqTlwBrI0CbYgixgs4gcY9HsH0CAwEAAQ==
    initialSize: 20
    minIdle: 10
    maxActive: 100
    maxWait: 60000
    validationQuery: SELECT 1
    filters: config,stat,wall
    testWhileIdle: true
  activemq:
    broker-url: tcp://10.10.200.7:61616
    in-memory: false
    user: admin
    password: admin
    packages:
      trust-all: true
    pool:
      enabled: true
      configuration:
        block-if-session-pool-is-full: true
        max-connections: 500
      idle-timeout: 5
      expiry-timeout: 5
  redis:
    database: 1
    host: 10.10.200.254
    password: ZDU0NTlkNDY5NWZi
    port: 6379
    pool:
      max-idle: 300
      min-idle: 100
      max-active: 300
      max-wait: -1
    timeout: 2000
  jpa:
    properties:
      hibernate:
        show_sql: true
server:
  port: 8080
  context-path: /pc-bet
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
second:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.200.255:3306/pc_game_record?useUnicode\=true&characterEncoding\=utf8
    username: root
    password: k7VqvQSWgN9FYB9kcheiD9VYk5jmU2AosuTS7NiiAwfbPjHs9QACSab81kh9SEoeVOc34k+sGaCA6cDAmI/D9Q==
    connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAN+p5nLVsEWh5I24zKhZzpbVlNxBsqBPJO2exeEvgAWYjYCDCnaEGpCk0GECLHqTlwBrI0CbYgixgs4gcY9HsH0CAwEAAQ==
    initialSize: 5
    minIdle: 5
    maxActive: 100
    maxWait: 60000
    validationQuery: SELECT 1
    filters: config,stat
    testWhileIdle: true